version: '3.8'

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5 
    tmpfs:
      - /var/lib/rabbitmq
    networks:
      - rabbitmq_network

  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Features__EnableRetry=true
      - Features__UseErrorFilter=true
    networks:
      - rabbitmq_network
    restart: on-failure

  producer:
    build:
      context: .
      dockerfile: Producer/Dockerfile
    container_name: producer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Features__UseErrorFilter=true
      - Worker__DelayInMs=1000
      - Worker__BatchSize=5000
      - Worker__MaxMessages=25000
    networks:
      - rabbitmq_network
    restart: on-failure

  # chaosmonkey:
  #   build:
  #     context: ./chaosmonkey
  #     dockerfile: Dockerfile
  #   container_name: chaosmonkey
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - RABBIT_HOST=rabbitmq
  #     - RABBIT_PORT=15672
  #     - RABBIT_USER=guest
  #     - RABBIT_PASS=guest
  #     - INTERVAL=10
  #   networks:
  #     - rabbitmq_network
  #   restart: on-failure

networks:
  rabbitmq_network:
    driver: bridge
